version: "3"
services:
  app:
    build: ./app
    links:
      - mongodb
    ports:
      - "5000:5000"
    image: leandrosev/docker_app2:flask_mongodb
      
    
  mongodb:
    image: mongo:3.6
    ports: 
      - "27017:27017"
      
